class Constant {
  static const String itemC = 'item';
  static const String itemP = 'itemJun';
  static const Map<String, String> common = {
    "item1": "토목건축공사업",
    "item2": "토목공사업",
    "item3": "건축공사업",
    "item4": "조경공사업",
    "item5": "산업ㆍ환경설비공사업",
  };
  static const Map<String, String> profession = {
    'itemJun1': "가스난방공사업",
    'itemJun2': "구조물해체ㆍ비계공사업",
    'itemJun3': "금속창호ㆍ지붕건축물조립공사업",
    'itemJun4': "기계가스설비공사업",
    'itemJun5': "도장ㆍ습식방수ㆍ석공사업",
    'itemJun6': "상ㆍ하수도설비공사업",
    'itemJun7': "수중ㆍ준설공사업",
    'itemJun8': "승강기ㆍ삭도공사업",
    'itemJun9': "실내건축공사업",
    'itemJun10': "조경식재ㆍ시설물설치공사업",
    'itemJun11': "지반조성ㆍ포장공사업",
    'itemJun12': "철강구조물공사업",
    'itemJun13': "철근ㆍ콘크리트공사업",
    'itemJun14': "철도ㆍ궤도공사업",
    'itemJun15': "가스시설시공업 제1종",
    'itemJun16': "가스시설시공업 제2종",
    'itemJun17': "가스시설시공업 제3종",
    'itemJun18': "강구조물공사업",
    'itemJun19': "건축물조립공사업",
    'itemJun20': "금속구조물ㆍ창호ㆍ온실공사업",
    'itemJun21': "기계설비공사업",
    'itemJun22': "난방시공업 제1종",
    'itemJun23': "난방시공업 제2종",
    'itemJun24': "난방시공업 제3종",
    'itemJun25': "도장공사업",
    'itemJun26': "미장ㆍ방수공사업",
    'itemJun27': "보링ㆍ그라우팅공사업",
    'itemJun28': "비계ㆍ구조물해체공사업",
    'itemJun29': "삭도설치공사업",
    'itemJun30': "상ㆍ하수도설비공사업",
    'itemJun31': "석공사업",
    'itemJun32': "수중공사업",
    'itemJun33': "습식ㆍ방수공사업",
    'itemJun34': "승강기설치공사업",
    'itemJun35': "시설물유지관리업",
    'itemJun36': "실내건축공사업",
    'itemJun37': "온실설치공사업",
    'itemJun38': "조경시설물설치공사업",
    'itemJun39': "조경식재공사업",
    'itemJun40': "조적공사업",
    'itemJun41': "준설공사업",
    'itemJun42': "지붕ㆍ판금공사업",
    'itemJun43': "지붕판금ㆍ건축물조립공사업",
    'itemJun44': "창호공사업",
    'itemJun45': "철강재설치공사업",
    'itemJun46': "철근ㆍ콘크리트공사업",
    'itemJun47': "철도ㆍ궤도공사업",
    'itemJun48': "철물공사업",
    'itemJun49': "토공사업",
    'itemJun50': "포장공사업"
  };
}
